### ISSUE TITLE
CORS issue with postMessage

### ISSUE THREAD

**Issue by VictorWesterlund** [Deltaco-AB/office-configurator#8]
https://github.com/Deltaco-AB/office-configurator/blob/c42940098dce51cc9b0ac36c09d84add2b9b8dcf/public/assets/js/module/Events.mjs#L6

`window.postMessage()` raises a CORS error when embedding the configurator using GH Pages. This is a major issue, since GH Pages is currently the recommended way to install the configuration.

----

console error from initial message type `ready` and general postMessage dispatcher
```
deltaco-ab.github.io/:1 Uncaught DOMException: Blocked a frame with origin "https://deltaco-ab.github.io" from accessing a cross-origin frame.
    at message (https://deltaco-ab.github.io/office-configurator/public/assets/js/module/Events.mjs:6:16)
    at https://deltaco-ab.github.io/office-configurator/public/assets/js/script.js:37:1
```

console error from `EventHandler.addProduct()`
```
Events.mjs:6 Uncaught DOMException: Blocked a frame with origin "https://deltaco-ab.github.io" from accessing a cross-origin frame.
    at message (https://deltaco-ab.github.io/office-configurator/public/assets/js/module/Events.mjs:6:16)
    at EventHandler.addProduct (https://deltaco-ab.github.io/office-configurator/public/assets/js/module/Events.mjs:39:3)
    at EventHandler.toggleProduct (https://deltaco-ab.github.io/office-configurator/public/assets/js/module/Events.mjs:80:8)
    at HTMLDivElement.<anonymous> (https://deltaco-ab.github.io/office-configurator/public/assets/js/module/Configurator.mjs:105:53)
```

**Comment by VictorWesterlund** [comment]
Fixed in issue #9
